name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Backend
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    # Frontend
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test || echo "No frontend tests found"

  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Deploy to server (via SSH)
  #     run: |
  #       ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
  #         cd /path/to/backend
  #         git pull origin main
  #         npm install
  #         pm2 restart backend-app

  #         cd /path/to/frontend
  #         git pull origin main
  #         npm install
  #         pm2 restart frontend-app
  #       EOF
  #     env:
  #       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
